### ISSUE TITLE
A tiny bug in the broyden function.

### ISSUE THREAD

**Issue by liruilong940607** [xuchen-ethz/snarf#1]
Great work and thanks for releasing the code!

I'm going through the code and it seems like there is a tiny bug that exists in the `broyden` function. It may or may not affect the results but I feel it's good to report it:

https://github.com/xuchen-ethz/snarf/blob/69b50ce796087c13d0094dd3b6d435ccaa678698/lib/model/broyden.py#L36

The code here should be `x_opt = x.clone()`. Otherwise the following code `x[ids_val] += delta_x[ids_val]` will also modify the values in the `x_opt`.

**Comment by xuchen-ethz** [comment]
Thank you for pointing this out! It's indeed safer to use clone here. 

In this particular case, it shouldn't make a difference though, because the interesting components in x_opt are overwritten by x after each update. I quickly tested and obtained identical training results with/without clone.  If you observe different behaviors, please let me know and I will look into this.

Thanks!
